/**
 * ErrorCodes - 业务错误码统一定义
 * 便于前端做精细化错误处理与国际化
 */

const ErrorCodes = {
    // 通用错误
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    INVALID_PARAMS: 'INVALID_PARAMS',
    UNAUTHORIZED: 'UNAUTHORIZED',

    // 订单相关
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
    ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
    ORDER_ALREADY_ACCEPTED: 'ORDER_ALREADY_ACCEPTED',
    ORDER_TIME_TOO_CLOSE: 'ORDER_TIME_TOO_CLOSE',
    ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
    ORDER_NOT_COMPLETED: 'ORDER_NOT_COMPLETED',
    ALREADY_ARRIVED: 'ALREADY_ARRIVED',
    MUST_ARRIVE_FIRST: 'MUST_ARRIVE_FIRST',

    // 财务相关
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    WITHDRAWAL_TOO_SMALL: 'WITHDRAWAL_TOO_SMALL',
    WITHDRAWAL_ALREADY_PROCESSED: 'WITHDRAWAL_ALREADY_PROCESSED',
    WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',

    // 权限相关
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    NOT_PROVIDER: 'NOT_PROVIDER',

    // 业务状态
    SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
    UNRECOGNIZED_SERVICE_TYPE: 'UNRECOGNIZED_SERVICE_TYPE',
    SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
    SETTLEMENT_ALREADY_DONE: 'SETTLEMENT_ALREADY_DONE',
    CANCEL_NEGOTIATION_INVALID: 'CANCEL_NEGOTIATION_INVALID'
};

module.exports = ErrorCodes;
